version: "3.9"

services:
  whisper-api:
    image: minhcuongdev/video-to-text
    build: .
    container_name: video-to-text
    restart: unless-stopped
    init: true
    ports:
      - 8000:8000